sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UGExeVK/M32tWEIykauN45kLHz/lhxRXBxLEGnWcJWMF6YGP7iVrAFNjPsaWI6ve4HNjATmpO5X8feD8ds+DtGkdyDvQgCThN+WwfvQpsf0R8HrvjKzD2p22i7zVc06xBjfTjd0Aut1S+TcTp9KYQXorC+RhjuoXhU3dun+uYqxDKEp7CohjilK84WBkne1ea/+5Oo9LzlW4Tz4J4fLjjgjy62g3vG0vczfrjhVhqfFGWu6JYlsqDGU6A4JFj3ZawoMf0juUqA9zW4PGgqPCLcc+PHB6G4iTcvMsv//wTL0HUQXNT6EDBHqGjAX/Qva5VdJ0Oo4Pt9eyD9wStlfHQQJzPcXmTpbHuLliW9ewbg/v8/uNTKk/sU9InDAMOHEHmx4oGqni0d0/AGlkjQiyu6lDxmnm5VZyMp2/hD1kaLYL0HRbTuVqh+WYhq5/H1d8xczltmzS42BZDTTDWgf7h6QfArVq6WikxQBo1oKbh+eMynFW2a2HT3FY86kqCAc3j8awa7wmzHhamtzzKjxm8rZq9dd8uKCSYsk1WcDW/5N1Y5/xXsd/uSzvX52QtLOLf6SIBj6LbYg4Uw/VUkpXmMH0QUuumEg83K2HTGMKiPBSmzd1xdthBRFbJuS6rYdSdpsjm7kRiYV2QlESqIzrv2uC7P/ozJeefi4cb6imCoo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Spell-of-the-Yukon-and-Other-Verses_207
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy